### ISSUE TITLE
[FEATURE] Créer un compte gmail LaGuidonette

### ISSUE THREAD

**Issue by MathysC** [MathysC/La-Guidonette#83]
[Documentation](https://www.jhipster.tech/tips/011_tip_configuring_email_in_jhipster.html)

Il faut créer un compte gmail pour LaGuidonette
Puis créer dans les paramètres de sécurité, un _"app password"_
Puis ajouter ses informations dans les fichiers `application-dev.yml` et `application-prod.yml` et `application-heroku.uml`

Dans **spring:**
```yml
mail:
    host: smtp.gmail.com
    port: 587
    username: <adresse mail>
    password: <app password>
    protocol: smtp
    tls: true
    properties.mail.smtp:
      auth: true
      starttls.enable: true
      ssl.trust: smtp.gmail.com
```

Dans **jhipster:**

Changer la valeur dans:

```yml
mail:
  base-url: <url>
```
